package com.example.design_system.theme

import androidx.compose.ui.graphics.Color

//Light - SunRise
//Light Default
val primarySunRise = Color(0xFF9C4200)
val onPrimarySunRise = Color(0xFFFFFFFF)
val primaryContainerSunRise = Color(0xFFFFDBC8)
val onPrimaryContainerSunRise = Color(0xFF331100)
val secondarySunRise = Color(0xFF77574C)
val onSecondarySunRise = Color(0xFFFFFFFF)
val secondaryContainerSunRise = Color(0xFFFFDBCE)
val onSecondaryContainerSunRise = Color(0xFF2C1600)
val tertiarySunRise = Color(0xFF665F30)
val onTertiarySunRise = Color(0xFFFFFFFF)
val tertiaryContainerSunRise = Color(0xFFF0E3A8)
val onTertiaryContainerSunRise = Color(0xFF201C00)
val errorSunRise = Color(0xFFBA1A1A)
val onErrorSunRise = Color(0xFFFFFFFF)
val errorContainerSunRise = Color(0xFFFFDAD6)
val onErrorContainerSunRise = Color(0xFF410002)
val backgroundSunRise = Color(0xFFFFFBFF)
val onBackgroundSunRise = Color(0xFF251913)
val surfaceSunRise = Color(0xFFFFFBFF)
val onSurfaceSunRise = Color(0xFF251913)
val surfaceVariantSunRise = Color(0xFFF5DED4)
val onSurfaceVariantSunRise = Color(0xFF53433C)
val outlineSunRise = Color(0xFF85736B)
val outlineVariantSunRise = Color(0xFFD8C2B8)
val scrimSunRise = Color(0xFF000000)
val inverseSurfaceSunRise = Color(0xFF3F2E27)
val inverseOnSurfaceSunRise = Color(0xFFFFEDE5)
val inversePrimarySunRise = Color(0xFFFFB68C)
val surfaceDimSunRise = Color(0xFFE8D6CE)
val surfaceBrightSunRise = Color(0xFFFFFBFF)
val surfaceContainerLowestSunRise = Color(0xFFFFFFFF)
val surfaceContainerLowSunRise = Color(0xFFFFF1EA)
val surfaceContainerSunRise = Color(0xFFFCEAE1)
val surfaceContainerHighSunRise = Color(0xFFF7E4DC)
val surfaceContainerHighestSunRise = Color(0xFFF1DED6)

//Light - Ocean
val primaryOcean = Color(0xFF0061A4)
val onPrimaryOcean = Color(0xFFFFFFFF)
val primaryContainerOcean = Color(0xFFD1E4FF)
val onPrimaryContainerOcean = Color(0xFF001D36)
val secondaryOcean = Color(0xFF535F70)
val onSecondaryOcean = Color(0xFFFFFFFF)
val secondaryContainerOcean = Color(0xFFD7E3F7)
val onSecondaryContainerOcean = Color(0xFF101C2B)
val tertiaryOcean = Color(0xFF6B5778)
val onTertiaryOcean = Color(0xFFFFFFFF)
val tertiaryContainerOcean = Color(0xFFF1DBFF)
val onTertiaryContainerOcean = Color(0xFF251431)
val errorOcean = Color(0xFFBA1A1A)
val onErrorOcean = Color(0xFFFFFFFF)
val errorContainerOcean = Color(0xFFFFDAD6)
val onErrorContainerOcean = Color(0xFF410002)
val backgroundOcean = Color(0xFFFDFCFF)
val onBackgroundOcean = Color(0xFF1A1C1E)
val surfaceOcean = Color(0xFFFDFCFF)
val onSurfaceOcean = Color(0xFF1A1C1E)
val surfaceVariantOcean = Color(0xFFDFE2EB)
val onSurfaceVariantOcean = Color(0xFF43474E)
val outlineOcean = Color(0xFF73777F)
val outlineVariantOcean = Color(0xFFC3C7CF)
val scrimOcean = Color(0xFF000000)
val inverseSurfaceOcean = Color(0xFF2F3033)
val inverseOnSurfaceOcean = Color(0xFFF1F0F4)
val inversePrimaryOcean = Color(0xFF9FCAFF)
val surfaceDimOcean = Color(0xFFDAD9DD)
val surfaceBrightOcean = Color(0xFFFDFCFF)
val surfaceContainerLowestOcean = Color(0xFFFFFFFF)
val surfaceContainerLowOcean = Color(0xFFF4F3F7)
val surfaceContainerOcean = Color(0xFFEEEDF1)
val surfaceContainerHighOcean = Color(0xFFE8E7EB)
val surfaceContainerHighestOcean = Color(0xFFE2E2E6)

//Light - Meadow
val primaryMeadow = Color(0xFF3C6939)
val onPrimaryMeadow = Color(0xFFFFFFFF)
val primaryContainerMeadow = Color(0xFFBEF0B5)
val onPrimaryContainerMeadow = Color(0xFF002204)
val secondaryMeadow = Color(0xFF53634F)
val onSecondaryMeadow = Color(0xFFFFFFFF)
val secondaryContainerMeadow = Color(0xFFD6E8CF)
val onSecondaryContainerMeadow = Color(0xFF111F0F)
val tertiaryMeadow = Color(0xFF38656A)
val onTertiaryMeadow = Color(0xFFFFFFFF)
val tertiaryContainerMeadow = Color(0xFFBCEBF0)
val onTertiaryContainerMeadow = Color(0xFF002023)
val errorMeadow = Color(0xFFBA1A1A)
val onErrorMeadow = Color(0xFFFFFFFF)
val errorContainerMeadow = Color(0xFFFFDAD6)
val onErrorContainerMeadow = Color(0xFF410002)
val backgroundMeadow = Color(0xFFFCFDF6)
val onBackgroundMeadow = Color(0xFF1A1C18)
val surfaceMeadow = Color(0xFFFCFDF6)
val onSurfaceMeadow = Color(0xFF1A1C18)
val surfaceVariantMeadow = Color(0xFFDEE5D8)
val onSurfaceVariantMeadow = Color(0xFF424940)
val outlineMeadow = Color(0xFF72796F)
val outlineVariantMeadow = Color(0xFFC2C9BD)
val scrimMeadow = Color(0xFF000000)
val inverseSurfaceMeadow = Color(0xFF2F312C)
val inverseOnSurfaceMeadow = Color(0xFFF1F2EA)
val inversePrimaryMeadow = Color(0xFFA3D39A)
val surfaceDimMeadow = Color(0xFFDBDCD5)
val surfaceBrightMeadow = Color(0xFFFCFDF6)
val surfaceContainerLowestMeadow = Color(0xFFFFFFFF)
val surfaceContainerLowMeadow = Color(0xFFF6F7EF)
val surfaceContainerMeadow = Color(0xFFF0F1E9)
val surfaceContainerHighMeadow = Color(0xFFEAEBE4)
val surfaceContainerHighestMeadow = Color(0xFFE5E6DE)

//Dark - Midnight
//Dark Default
val primaryMidnight = Color(0xFFC6B0FF)
val onPrimaryMidnight = Color(0xFF3A1A78)
val primaryContainerMidnight = Color(0xFF523190)
val onPrimaryContainerMidnight = Color(0xFFE9DDFF)
val secondaryMidnight = Color(0xFFCBC2DB)
val onSecondaryMidnight = Color(0xFF332D41)
val secondaryContainerMidnight = Color(0xFF4A4358)
val onSecondaryContainerMidnight = Color(0xFFE8DEF8)
val tertiaryMidnight = Color(0xFFEDB8CC)
val onTertiaryMidnight = Color(0xFF4A2536)
val tertiaryContainerMidnight = Color(0xFF643B4C)
val onTertiaryContainerMidnight = Color(0xFFFFD9E6)
val errorMidnight = Color(0xFFFFB4AB)
val onErrorMidnight = Color(0xFF690005)
val errorContainerMidnight = Color(0xFF93000A)
val onErrorContainerMidnight = Color(0xFFFFDAD6)
val backgroundMidnight = Color(0xFF1C1B1E)
val onBackgroundMidnight = Color(0xFFE6E1E6)
val surfaceMidnight = Color(0xFF1C1B1E)
val onSurfaceMidnight = Color(0xFFE6E1E6)
val surfaceVariantMidnight = Color(0xFF49454E)
val onSurfaceVariantMidnight = Color(0xFFCBC4CF)
val outlineMidnight = Color(0xFF958E99)
val outlineVariantMidnight = Color(0xFF49454E)
val scrimMidnight = Color(0xFF000000)
val inverseSurfaceMidnight = Color(0xFFE6E1E6)
val inverseOnSurfaceMidnight = Color(0xFF313033)
val inversePrimaryMidnight = Color(0xFF6C4CA5)
val surfaceDimMidnight = Color(0xFF1C1B1E)
val surfaceBrightMidnight = Color(0xFF433F44)
val surfaceContainerLowestMidnight = Color(0xFF120F13)
val surfaceContainerLowMidnight = Color(0xFF241F27)
val surfaceContainerMidnight = Color(0xFF29232C)
val surfaceContainerHighMidnight = Color(0xFF332D37)
val surfaceContainerHighestMidnight = Color(0xFF3F3742)

//Dark - DeepSpace
val primaryDeepSpace = Color(0xFFADC6FF)
val onPrimaryDeepSpace = Color(0xFF002F6C)
val primaryContainerDeepSpace = Color(0xFF00458F)
val onPrimaryContainerDeepSpace = Color(0xFFD8E2FF)
val secondaryDeepSpace = Color(0xFFBFC6DC)
val onSecondaryDeepSpace = Color(0xFF293042)
val secondaryContainerDeepSpace = Color(0xFF3F4759)
val onSecondaryContainerDeepSpace = Color(0xFFDBE2F9)
val tertiaryDeepSpace = Color(0xFFD5BEE1)
val onTertiaryDeepSpace = Color(0xFF3B2947)
val tertiaryContainerDeepSpace = Color(0xFF523F5F)
val onTertiaryContainerDeepSpace = Color(0xFFF1DAFF)
val errorDeepSpace = Color(0xFFFFB4AB)
val onErrorDeepSpace = Color(0xFF690005)
val errorContainerDeepSpace = Color(0xFF93000A)
val onErrorContainerDeepSpace = Color(0xFFFFDAD6)
val backgroundDeepSpace = Color(0xFF1B1B1F)
val onBackgroundDeepSpace = Color(0xFFE3E2E6)
val surfaceDeepSpace = Color(0xFF1B1B1F)
val onSurfaceDeepSpace = Color(0xFFE3E2E6)
val surfaceVariantDeepSpace = Color(0xFF44474F)
val onSurfaceVariantDeepSpace = Color(0xFFC4C6D0)
val outlineDeepSpace = Color(0xFF8E9099)
val outlineVariantDeepSpace = Color(0xFF44474F)
val scrimDeepSpace = Color(0xFF000000)
val inverseSurfaceDeepSpace = Color(0xFFE3E2E6)
val inverseOnSurfaceDeepSpace = Color(0xFF303034)
val inversePrimaryDeepSpace = Color(0xFF2E5FA3)
val surfaceDimDeepSpace = Color(0xFF1B1B1F)
val surfaceBrightDeepSpace = Color(0xFF414045)
val surfaceContainerLowestDeepSpace = Color(0xFF101013)
val surfaceContainerLowDeepSpace = Color(0xFF232327)
val surfaceContainerDeepSpace = Color(0xFF27272B)
val surfaceContainerHighDeepSpace = Color(0xFF313035)
val surfaceContainerHighestDeepSpace = Color(0xFF3C3B40)

//Dark - Ember
val primaryEmber = Color(0xFFFFB59C)
val onPrimaryEmber = Color(0xFF5C1A00)
val primaryContainerEmber = Color(0xFF812800)
val onPrimaryContainerEmber = Color(0xFFFFDBCE)
val secondaryEmber = Color(0xFFE7BDB1)
val onSecondaryEmber = Color(0xFF442A22)
val secondaryContainerEmber = Color(0xFF5D4037)
val onSecondaryContainerEmber = Color(0xFFFFDBCE)
val tertiaryEmber = Color(0xFFD3C88D)
val onTertiaryEmber = Color(0xFF383005)
val tertiaryContainerEmber = Color(0xFF50461A)
val onTertiaryContainerEmber = Color(0xFFF0E4A8)
val errorEmber = Color(0xFFFFB4AB)
val onErrorEmber = Color(0xFF690005)
val errorContainerEmber = Color(0xFF93000A)
val onErrorContainerEmber = Color(0xFFFFDAD6)
val backgroundEmber = Color(0xFF201A18)
val onBackgroundEmber = Color(0xFFEDE0DC)
val surfaceEmber = Color(0xFF201A18)
val onSurfaceEmber = Color(0xFFEDE0DC)
val surfaceVariantEmber = Color(0xFF53433D)
val onSurfaceVariantEmber = Color(0xFFD8C2BA)
val outlineEmber = Color(0xFFA08D85)
val outlineVariantEmber = Color(0xFF53433D)
val scrimEmber = Color(0xFF000000)
val inverseSurfaceEmber = Color(0xFFEDE0DC)
val inverseOnSurfaceEmber = Color(0xFF362F2C)
val inversePrimaryEmber = Color(0xFFA23F00)
val surfaceDimEmber = Color(0xFF201A18)
val surfaceBrightEmber = Color(0xFF473D3A)
val surfaceContainerLowestEmber = Color(0xFF1A1513)
val surfaceContainerLowEmber = Color(0xFF28211F)
val surfaceContainerEmber = Color(0xFF2D2523)
val surfaceContainerHighEmber = Color(0xFF37302D)
val surfaceContainerHighestEmber = Color(0xFF433B37)

val Red = Color(0xFFFF0000)
val Orange = Color(0xFFFFA500)
val Yellow = Color(0xFFFFFF00)
val Green = Color(0xFF00FF00)
val Blue = Color(0xFF0000FF)
val Indigo = Color(0xFF003366)
val Violet = Color(0xFF8A2BE2)

val priorityColors = listOf(
    Violet,
    Orange,
    Red,
)

val Crimson = Color(0xFFF01F55)
val Cobalt = Color(0xFF1F4DF0)
val Emerald = Color(0xFF1FF03D)
val Amber = Color(0xFFF0B81F)
val Mauve = Color(0xFF9B485C)

val flagColors = listOf(
    Crimson,
    Cobalt,
    Emerald,
    Amber,
    Mauve,
)